export const Colors = {
  whiteColor: "#fff",
  orangeColor: "#FF6901",
  redColor: "#FE1700",
  pinkColor: "#FDFCFC",
  borderColor: "#ddd",
  greyishBlueColor: "#A09CAB",
  darkGreyColor: "#1A1A1A",
  lightGreyColor: "#B2B2B2",
  blackColor: "#000",
  mediumDarkGrey: "#666",
  tabSelectionColor: "#EDEDED59",
  tableRowColor: "#D9D9D9",
  expenseColor: "#4caf50",
  expenseErrorColor: "#f44336",
  leaveBakcgroundColor: "#28a745",
  presentColor: "#7086FD",
  leaveColor: "#6FD195",
  wfhColor: "#FFAE4C",
};
